"""Regenerate docs/tool-reference.md from the live tool registry.

The reference is generated so it cannot drift from the schemas the model actually sees.
"""

from __future__ import annotations

import asyncio
import json
from inspect import cleandoc
from pathlib import Path

from baglens import __version__
from baglens.server import build_server

NAMESPACE_BLURB = {
    "health": "The integrity auditor. Call these before drawing conclusions from a recording.",
    "inspect": "Single-mission reads. Cheap, hard-capped, and the right place to start.",
    "timeseries": "Numeric analysis. Returns statistics, never payloads.",
    "catalog": "The corpus layer. Index once, query forever.",
    "compare": "Cross-mission comparison — what makes this a fleet tool.",
    "logs": "Text and diagnostics, compressed into patterns rather than lines.",
    "spatial": "Trajectory and transform-tree analysis.",
    "frames": "The multimodal bridge: timestamps to images a vision model can read.",
    "pointcloud": "Lidar summarised statistically; rendering is opt-in.",
    "export": "Shareable evidence. Read-only on sources; only ever writes new files.",
}


def schema_of(tool: object) -> dict:
    return getattr(tool, "input_schema", None) or getattr(tool, "inputSchema", None) or {}


def render() -> str:
    server = build_server()
    tools = asyncio.run(server.list_tools())
    by_ns: dict[str, list] = {}
    for tool in tools:
        by_ns.setdefault(tool.name.split(".")[0], []).append(tool)

    lines = [
        "# Tool reference",
        "",
        f"`baglens` {__version__} — **{len(tools)} tools** across {len(by_ns)} namespaces.",
        "",
        "Every tool returns a typed Pydantic model. Every result that reports on data",
        "carries a `provenance` object naming the recording, the topics, the time range and",
        "the method used. Every result is token-budgeted: if `truncated` is true, read",
        "`suggested_narrowing` and ask a narrower question rather than retrying.",
        "",
        "_Generated by `scripts/gen_tool_reference.py` — do not edit by hand._",
        "",
    ]

    for ns in sorted(by_ns):
        lines += [f"## `{ns}.*`", "", NAMESPACE_BLURB.get(ns, ""), ""]
        for tool in sorted(by_ns[ns], key=lambda t: t.name):
            schema = schema_of(tool)
            props = schema.get("properties", {}) or {}
            required = set(schema.get("required", []) or [])
            # docstrings arrive with their source indentation; cleandoc so the markdown
            # does not render every description as a code block
            lines += [f"### `{tool.name}`", "", cleandoc(tool.description or ""), ""]
            if props:
                lines += ["| parameter | type | required | default |", "|---|---|---|---|"]
                for name, spec in props.items():
                    typ = spec.get("type") or spec.get("anyOf") and "union" or "any"
                    default = spec.get("default", "")
                    lines.append(
                        f"| `{name}` | {typ} | {'yes' if name in required else 'no'} | "
                        f"`{json.dumps(default)}` |"
                        if default != "" or name not in required
                        else f"| `{name}` | {typ} | yes | |"
                    )
                lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    out = Path(__file__).resolve().parents[1] / "docs" / "tool-reference.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render())
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
